export const GOOGLE_AUTH = 'GOOGLE_AUTH';

export const SET_DAREME_INITIAL = 'SET_DAREME_INITIAL';
export const SET_DAREME_DETAIL_INITIAL = 'SET_DAREME_DETAIL_INITIAL';
export const SET_DAREMES = 'SET_DAREMES';
export const SET_DAREME = 'SET_DAREME';

//FundMe
export const SET_FUNDME_INITIAL = 'SET_FUNDME_INITIAL';
export const SET_FUNDME_DETAIL_INITIAL = 'SET_FUNDME_DETAIL_INITIAL';
export const SET_FUNDMES = 'SET_FUNDMES';
export const SET_FUNDME = 'SET_FUNDME';
export const SET_FUNDME_VOTES = 'SET_FUNDME_VOTES';

export const SET_TEASER_FILE = "SET_TEASER_FILE";
export const SET_COVER_FILE = "SET_COVER_FILE";
export const SET_TEASER_FILE1 = "SET_TEASER_FILE1";
export const SET_COVER_FILE1 = "SET_COVER_FILE1";

export const SET_USER = 'SET_USER';
export const SET_NAME_EXIST = 'SET_NAME_EXIST';
export const SET_URL_EXIST = 'SET_URL_EXIST';
export const SET_USERS = 'SET_USERS';
export const SET_USER_INITIAL = 'SET_USER_INITIAL';
export const SET_STRIPEID = 'SET_STRIPEID';
export const SET_LANGUAGE = 'SET_LANGUAGE';

export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE';

export const SET_FANWALL = 'SET_FANWALL';
export const SET_FANWALLS = 'SET_FANWALLS';
export const SET_FANWALL_INITIAL = 'SET_FANWALL_INITIAL';
export const SET_FANWALL_TYPE = 'SET_FANWALL_TYPE';

export const SET_TIPS = 'SET_TIPS';
export const SET_TIP = 'SET_TIP';

export const SET_PREVIOUS_ROUTE = 'SET_PREVIOUS_ROUTE';
export const SET_NEXT_ROUTE = 'SET_NEXT_ROUTE';
export const SET_DIALOG_STATE = 'SET_DIALOG_STATE';
export const SET_CURRENT_DAREME = 'SET_CURRENT_DAREME';
export const SET_CURRENT_FUNDME = 'SET_CURRENT_FUNDME';

export const SET_PROFILE_DATA = 'SET_PROFILE_DATA'

export const SET_ADMIN_TITLE = 'SET_ADMIN_TITLE';
export const SET_ADMIN_CATEGORY = 'SET_ADMIN_CATEGORY';
export const SET_ADMIN_OPTIONS = 'SET_ADMIN_OPTIONS';
export const SET_ADMIN_TEASER_SIZE_TYPE = 'SET_ADMIN_TEASER_SIZE_TYPE';
export const SET_FANWALL_VIDEOFILE = 'SET_FANWALL_VIDEOFILE'
export const SET_FANWALL_VIDEO_SIZETYPE = 'SET_FANWALL_VIDEO_SIZETYPE'
export const SET_FANWALL_COVERFILE = 'SET_FANWALL_COVERFILE'

export const SET_NOTIFICATION_LIST = "SET_NOTIFICATION_LIST";
export const SET_NOTIFICATION_SETTING = 'SET_NOTIFICATION_SETTING';
export const SET_NOTIFICATION_TYPES = 'SET_NOTIFICATION_TYPES';

export const SET_DONUTS_INFO = "SET_DONUTS_INFO";
export const SET_ADMIN_DONUTS = "SET_ADMIN_DONUTS";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";

export const SET_OPTION_LOGS = "SET_OPTION_LOGS";
export const SET_REFUND_DONUTS = "SET_REFUND_DONUTS";
export const SET_TIPID = 'SET_TIPID'
export const SET_PAYMENT = 'SET_PAYMENT'

export const SET_VIDEOFILE = 'SET_VIDEOFILE'
export const SET_COVERFILE = 'SET_COVERFILE'
export const SET_SIZETYPE = 'SET_SIZETYPE'
export const SET_COVERINDEX = 'SET_COVERINDEX'

export const SET_TIPAVAILABLE = 'SET_TIPAVAILABLE'
export const SET_TIPFUNCTION = 'SET_TIPFUNCTION'

export const SET_REFERRALLINKS = 'SET_REFERRALLINKS'
export const SET_REFERRALLINK = 'SET_REFERRALLINK'
export const SET_REFERRAL_REWARD = 'SET_REFERRAL_REWARD'
export const UPDATE_REFERRAL_LINKS = 'UPDATE_REFERRAL_LINKS'